### ISSUE TITLE
Unused items in your css

### ISSUE THREAD

**Issue by farishkash** [prosaicpoet123/prj-rev-bwfs-dasmoto#2]
You already have this covered with this line here

```
h1, h2, h3, span {
  | font-weight: bold;
  | }
```

so make sure you delete this here

```
p span {
  | color: blue;
  | }
  |  
  | .bold {
  | font-weight: bold;
  | }

```

I assuming this was just missed or forgotten because you don't have the bold class in your html as far as I can tell.

**Comment by prosaicpoet123** [comment]
Yes that was a mistake. I originally used the targeter p span, but then decided to group them.

Sent from my iPhone

On 8 Jul 2017, at 21:17, Farish Kashefinejad <notifications@github.com<mailto:notifications@github.com>> wrote:


You already have this covered with this line here

h1, h2, h3, span {
  | font-weight: bold;
  | }


so make sure you delete this here

p span {
  | color: blue;
  | }
  |
  | .bold {
  | font-weight: bold;
  | }



I assuming this was just missed or forgotten because you don't have the bold class in your html as far as I can tell.

**Comment by prosaicpoet123** [comment]
Sorry, I meant .bold

Sent from my iPhone

On 8 Jul 2017, at 21:17, Farish Kashefinejad <notifications@github.com<mailto:notifications@github.com>> wrote:


You already have this covered with this line here

h1, h2, h3, span {
  | font-weight: bold;
  | }


so make sure you delete this here

p span {
  | color: blue;
  | }
  |
  | .bold {
  | font-weight: bold;
  | }



I assuming this was just missed or forgotten because you don't have the bold class in your html as far as I can tell.
